version: "3"
services:
    elasticsearch:
        image: elasticsearch:7.7.0
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elknetwork
    kibana:
        image: kibana:7.7.0
        container_name: kibana
        hostname: kibana
        ports:
            - 5601:5601
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    logstash:
        image: logstash:7.7.0
        container_name: logstash
        hostname: logstash
        ports:
            - 9600:9600
            - 8089:8089
        volumes:
          - .\logstash:/usr/share/logstash/pipeline/
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    app:
        image: harisshafiq09/sample-app:latest
        container_name: app
        command: /var/sample-app
        ports:
            - 8083:8083
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:8089"
        networks:
          - elknetwork
networks:
    elknetwork:
        driver: bridge